import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Button, Card, CardContent, CardHeader, Chip, CircularProgress, Divider, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography, } from "@mui/material";
export function TodoPanel({ categories, todosByCategory, isLoading, errorMessage, fieldErrors, title, description, categoryId, dueDate, minDueDate, editingId, onTitleChange, onDescriptionChange, onCategoryChange, onDueDateChange, onSubmit, onCancel, onEditStart, onToggleStatus, onDeleteTodo, formatDate, currentPage, totalPages, onPageChange, pageSize, totalCount, }) {
    return (_jsxs(Card, { children: [_jsx(CardHeader, { title: editingId ? "Edit Todo" : "Add Todo" }), _jsxs(CardContent, { children: [_jsxs(Stack, { spacing: 2, children: [errorMessage && (_jsx(Typography, { color: "error", variant: "body2", children: errorMessage })), _jsx(TextField, { label: "Todo title", value: title, onChange: e => onTitleChange(e.target.value), fullWidth: true, error: Boolean(fieldErrors.title), helperText: fieldErrors.title }), _jsx(TextField, { label: "Description", value: description, onChange: e => onDescriptionChange(e.target.value), multiline: true, minRows: 2, fullWidth: true }), _jsxs(Stack, { direction: { xs: "column", sm: "row" }, spacing: 2, children: [_jsxs(FormControl, { fullWidth: true, children: [_jsx(InputLabel, { id: "category-select-label", children: "Category" }), _jsxs(Select, { labelId: "category-select-label", value: categoryId, label: "Category", onChange: e => onCategoryChange(e.target.value), error: Boolean(fieldErrors.categoryId), children: [_jsx(MenuItem, { value: "", children: _jsx("em", { children: "Select category" }) }), categories.map(cat => (_jsx(MenuItem, { value: cat.id, children: cat.name }, cat.id)))] })] }), _jsx(TextField, { label: "Due date", type: "date", InputLabelProps: { shrink: true }, value: dueDate, onChange: e => onDueDateChange(e.target.value), fullWidth: true, inputProps: { min: minDueDate }, error: Boolean(fieldErrors.dueDate), helperText: fieldErrors.dueDate })] }), _jsxs(Stack, { direction: "row", spacing: 2, children: [_jsx(Button, { variant: "contained", onClick: onSubmit, children: editingId ? "Save Changes" : "Add Todo" }), editingId && (_jsx(Button, { variant: "text", onClick: onCancel, children: "Cancel" }))] })] }), _jsx(Divider, { sx: { my: 3 } }), isLoading ? (_jsx(Stack, { alignItems: "center", py: 3, children: _jsx(CircularProgress, {}) })) : (Object.entries(todosByCategory).map(([categoryName, list]) => (_jsxs(Box, { mb: 3, children: [_jsxs(Stack, { direction: "row", alignItems: "center", justifyContent: "space-between", mb: 1, children: [_jsx(Typography, { fontWeight: 700, children: categoryName }), _jsx(Chip, { label: `${list.length} items`, size: "small" })] }), _jsx(Stack, { spacing: 1.5, children: list.map(todo => (_jsx(Card, { variant: "outlined", children: _jsxs(CardContent, { sx: {
                                            display: "flex",
                                            justifyContent: "space-between",
                                            alignItems: "center",
                                            gap: 2,
                                        }, children: [_jsxs(Box, { sx: { flex: 1 }, children: [_jsxs(Stack, { direction: "row", spacing: 1, alignItems: "center", children: [_jsx(Typography, { fontWeight: 700, sx: { textDecoration: todo.completed ? "line-through" : "none" }, children: todo.title }), _jsx(Chip, { label: todo.completed ? "Completed" : "Active", color: todo.completed ? "success" : "warning", size: "small" })] }), todo.description && (_jsx(Typography, { variant: "body2", color: "text.secondary", children: todo.description })), _jsxs(Typography, { variant: "caption", color: "text.secondary", children: ["Due ", formatDate(todo.dueDate), " | Created ", formatDate(todo.createdAt)] })] }), _jsxs(Stack, { direction: "row", spacing: 1, children: [_jsx(Button, { variant: "outlined", onClick: () => onToggleStatus(todo.id), children: todo.completed ? "Mark Incomplete" : "Mark Complete" }), _jsx(Button, { variant: "outlined", onClick: () => onEditStart(todo), children: "Edit" }), _jsx(Button, { variant: "outlined", color: "error", onClick: () => onDeleteTodo(todo.id), children: "Delete" })] })] }) }, todo.id))) })] }, categoryName)))), _jsxs(Stack, { direction: "row", justifyContent: "space-between", alignItems: "center", mt: 2, children: [_jsxs(Typography, { variant: "body2", children: ["Page ", currentPage, " of ", totalPages, " \u2022 Showing up to ", pageSize, " per page \u2022 ", totalCount, " total"] }), _jsxs(Stack, { direction: "row", spacing: 1, children: [_jsx(Button, { variant: "outlined", disabled: currentPage <= 1, onClick: () => onPageChange(currentPage - 1), children: "Previous" }), _jsx(Button, { variant: "outlined", disabled: currentPage >= totalPages, onClick: () => onPageChange(currentPage + 1), children: "Next" })] })] })] })] }));
}
